# Generated by Django 3.2.3 on 2022-03-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(default='', max_length=200)),
                ('percentages', models.CharField(default='', max_length=200)),
                ('dates', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
